export const COMPANY_REPOSITORY = "COMPANY_REPOSITORY";
export const USER_REPOSITORY = "USER_REPOSITORY";
export const CUSTOMER_REPOSITORY = "CUSTOMER_REPOSITORY";
export const PASSWORD_HASHER = "PASSWORD_HASHER";
export const TOKEN_SERVICE = "TOKEN_SERVICE";
export const REPORTING_GATEWAY = "REPORTING_GATEWAY";
